<?php

namespace Database\Seeders;

use App\Models\DocumentType;
use Illuminate\Database\Seeder;

class DocumentTypeSeeder extends Seeder
{
    public function run(): void
    {
        $types = [
            [
                'name' => 'KTP Direktur',
                'code' => 'KTP_DIREKTUR',
                'description' => 'Kartu Tanda Penduduk (KTP) asli Direktur / Penanggung Jawab Perusahaan.',
                'allowed_extensions' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size_mb' => 5,
                'icon' => 'heroicon-o-identification',
                'weight' => 5,
                'is_required' => true,
                'validity_days' => null,
                'is_active' => true,
            ],
            [
                'name' => 'NPWP Perusahaan',
                'code' => 'NPWP_PERUSAHAAN',
                'description' => 'Nomor Pokok Wajib Pajak (NPWP) Badan/Perusahaan Pers.',
                'allowed_extensions' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size_mb' => 5,
                'icon' => 'heroicon-o-credit-card',
                'weight' => 10,
                'is_required' => true,
                'validity_days' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Norek Bank',
                'code' => 'NOREK_BANK',
                'description' => 'Buku Rekening / Surat Keterangan Nomor Rekening Bank milik Perusahaan.',
                'allowed_extensions' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size_mb' => 5,
                'icon' => 'heroicon-o-building-library',
                'weight' => 5,
                'is_required' => true,
                'validity_days' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Akta Notaris',
                'code' => 'AKTA_NOTARIS',
                'description' => 'Akta Notaris Pendirian Perusahaan Pers beserta perubahan terakhirnya.',
                'allowed_extensions' => ['pdf'],
                'max_file_size_mb' => 10,
                'icon' => 'heroicon-o-document-text',
                'weight' => 10,
                'is_required' => true,
                'validity_days' => null,
                'is_active' => true,
            ],
            [
                'name' => 'IUP NIB',
                'code' => 'IUP_NIB',
                'description' => 'Izin Usaha / Nomor Induk Berusaha (NIB) aktif dari Lembaga OSS.',
                'allowed_extensions' => ['pdf'],
                'max_file_size_mb' => 5,
                'icon' => 'heroicon-o-briefcase',
                'weight' => 10,
                'is_required' => true,
                'validity_days' => null,
                'is_active' => true,
            ],
            [
                'name' => 'SKT (Surat Keterangan Terdaftar Pajak)',
                'code' => 'SKT_PAJAK',
                'description' => 'Surat Keterangan Terdaftar (SKT) dari Direktorat Jenderal Pajak.',
                'allowed_extensions' => ['pdf'],
                'max_file_size_mb' => 5,
                'icon' => 'heroicon-o-document-check',
                'weight' => 5,
                'is_required' => true,
                'validity_days' => null,
                'is_active' => true,
            ],
            [
                'name' => 'PKP (Pengusaha Kena Pajak)',
                'code' => 'PKP',
                'description' => 'Surat Pengukuhan Pengusaha Kena Pajak (PKP) Perusahaan.',
                'allowed_extensions' => ['pdf'],
                'max_file_size_mb' => 5,
                'icon' => 'heroicon-o-check-badge',
                'weight' => 5,
                'is_required' => true,
                'validity_days' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Pengesahan SK Kemenkumham',
                'code' => 'SK_KEMENKUMHAM',
                'description' => 'Surat Keputusan Pengesahan Badan Hukum Perusahaan dari Kemenkumham.',
                'allowed_extensions' => ['pdf'],
                'max_file_size_mb' => 5,
                'icon' => 'heroicon-o-shield-check',
                'weight' => 10,
                'is_required' => true,
                'validity_days' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Sertifikat Dewan PERS',
                'code' => 'SERTIFIKAT_DEWAN_PERS',
                'description' => 'Sertifikat Verifikasi Faktual / Administrasi dari Dewan Pers.',
                'allowed_extensions' => ['pdf'],
                'max_file_size_mb' => 5,
                'icon' => 'heroicon-o-award',
                'weight' => 10,
                'is_required' => true,
                'validity_days' => 1825,
                'is_active' => true,
            ],
            [
                'name' => 'Sertifikat Organisasi PERS Media (JMSI/SMSI/AMSI)',
                'code' => 'ORGANISASI_PERS',
                'description' => 'Sertifikat Keanggotaan Organisasi Perusahaan Pers (JMSI, SMSI, AMSI, dsb).',
                'allowed_extensions' => ['pdf'],
                'max_file_size_mb' => 5,
                'icon' => 'heroicon-o-user-group',
                'weight' => 5,
                'is_required' => true,
                'validity_days' => 365,
                'is_active' => true,
            ],
            [
                'name' => 'Sertifikat Kompetensi Wartawan UTAMA',
                'code' => 'UKW_UTAMA',
                'description' => 'Sertifikat Uji Kompetensi Wartawan (UKW) tingkat UTAMA Pemred / Wartawan.',
                'allowed_extensions' => ['pdf'],
                'max_file_size_mb' => 5,
                'icon' => 'heroicon-o-academic-cap',
                'weight' => 10,
                'is_required' => true,
                'validity_days' => 1825,
                'is_active' => true,
            ],
            [
                'name' => 'KTP yang Bersetifikasi Kompetensi Wartawan UTAMA',
                'code' => 'KTP_WARTAWAN_UTAMA',
                'description' => 'Kartu Tanda Penduduk (KTP) milik Wartawan Utama pemegang sertifikat.',
                'allowed_extensions' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size_mb' => 5,
                'icon' => 'heroicon-o-identification',
                'weight' => 5,
                'is_required' => true,
                'validity_days' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Surat Penawaran',
                'code' => 'SURAT_PENAWARAN',
                'description' => 'Surat Penawaran Resmi Kerjasama Media beserta Price List / Tarif Iklan.',
                'allowed_extensions' => ['pdf'],
                'max_file_size_mb' => 10,
                'icon' => 'heroicon-o-document-currency-dollar',
                'weight' => 10,
                'is_required' => true,
                'validity_days' => 365,
                'is_active' => true,
            ],
        ];

        foreach ($types as $type) {
            DocumentType::updateOrCreate(['code' => $type['code']], $type);
        }
    }
}
